### ISSUE TITLE
Negation seem to not be taken in consideration in the lexicon classifier

### ISSUE THREAD

**Issue by vincentteyssier** [konstantinkobs/emote-controlled#3]
Hi, excellent work in this paper, very informative.

I was looking at the code and the tokenizer is adding the _NEG to signify a negation preceding the token.

```
for token in msg_tokens:
                if token.endswith("_NEG"):
                    token = token.replace("_NEG", "")
                if token in self.lexicon:
                    prob_list.append(self.lexicon[token])
```

When you add the sentiment score to the prob_list however, since you have stripped the _NEG before to be able to match it to a lexicon token, there has not been any mechanism to reflect the negation on this token.

Am I understanding right?

If yes  then maybe the scores should be rebalanced by inverting the negative and positive values for the token.
What do you think?

I would do something like this:

```
if token in self.lexicon:
    if token.endswith("_NEG"):
        token_score['positive'] = self.lexicon[token.replace("_NEG", "")]['negative']
        token_score['negative'] = self.lexicon[token.replace("_NEG", "")]['positive']
        token_score['neutral'] = self.lexicon[token.replace("_NEG", "")]['neutral']
        prob_list.append(token_score)
    else:
        prob_list.append(self.lexicon[token])
```

**Comment by konstantinkobs** [comment]
Hey, thank you very much for your kind words!

You are correct, we do not use the negation information for distribution-based approach. I do not really remember if this did not increase the performance or there were other problems.

I invite you to test your idea, which seams straight-forward and easy to implement, and submit a pull request, if this in fact performs better. 😄 From a research stand point, this might be a possible improvement which could be published (with maybe other improvements and some analyses what cases the improved method performs better on). Feel free to experiment. 🧪

Have a great day and thank you!
